function study = study_template()
%STUDY_TEMPLATE Minimal template for a new modular study.
%
% Copy this file, rename the function, and edit the ADC/stages/analyses.

study = struct();
study.name = "My SD92xx ADC study";
study.description = "Edit this description.";

%% ADC selection

study.adc = block_adc_sd92xx( ...
    "Variant", "SD9231-20-A-QC9-TA", ...
    "SampleRate_Hz", 20e6 ...
);

% Alternative selection by family properties:
% study.adc = block_adc_sd92xx( ...
%     "ResolutionBits", 10, ...
%     "SpeedGrade_MSps", 40, ...
%     "SampleRate_Hz", 10e6 ...
% );

%% Signal chain

study.stages = { ...
    block_analog_lpf("Cutoff_Hz", 10e3, "Order", 2), ...
    block_adc_sampler(), ...
    block_cic_decimator("Decimation", 4, "Order", 8), ...
    block_fir_decimator("Decimation", 3, "Cutoff_Hz", 10e3) ...
};

%% Analyses

study.analyses = { ...
    analysis_chain_response("FMax_Hz", 1.8e6), ...
    analysis_alias_map("FMax_Hz", 1.8e6, "AliasBand_Hz", [0 10e3]) ...
};

end
